language: elixir
elixir: '1.7.1'
otp_release: '21.0'

sudo: required

services:
  - docker

install:
  - docker build -t rschaden/battlemap .

script:
  - docker network create test
  - docker run --network test --name postgres -d -e POSTGRES_PASSWORD=postgres mdillon/postgis
  - docker run --network test -e MIX_ENV=test -e POSTGRES_HOST=postgres rschaden/battlemap mix test
