language: elixir
elixir: '1.5.2'
otp_release: '20.0'

sudo: required

services:
  - docker

install:
  - docker build -t rschaden/battlemap .

script:
  - docker run -e MIX_ENV=test rschaden/battlemap mix test
